/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class opennlp_ccg_ngrams_SRILMNgramModel */

#ifndef _Included_opennlp_ccg_ngrams_SRILMNgramModel
#define _Included_opennlp_ccg_ngrams_SRILMNgramModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     opennlp_ccg_ngrams_SRILMNgramModel
 * Method:    loadLM
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_opennlp_ccg_ngrams_SRILMNgramModel_loadLM
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     opennlp_ccg_ngrams_SRILMNgramModel
 * Method:    doLogProb
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_opennlp_ccg_ngrams_SRILMNgramModel_doLogProb
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     opennlp_ccg_ngrams_SRILMNgramModel
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_opennlp_ccg_ngrams_SRILMNgramModel_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
